const IMAGE = {
  HOME_ICON: require("../../assets/home.png"),
  HOME_SELECTED_ICON: require("../../assets/home-selected.png"),
  SETTINGS_ICON: require("../../assets/settings.png"),
  SETTINGS_SELECTED_ICON: require("../../assets/settings-selected.png"),
  MENU_ICON: require("../../assets/hamburger.png"),
  BACK_ICON: require("../../assets/left.png"),
  BACKGROUND_IMAGE: require("../../assets/images/bg.jpg"),
  SLIDE_IMAGE_1: require("../../assets/images/slide/1.jpg"),
};


const ENTranslates = {
  "Log In": "Log In",
  "Sign Up": "Sign Up",
  "Sign Out": "Sign Out",
  "Home": "Home",
  "Email or Phone number": "Email or Phone number",
  "Password": "Password",
  "Forgot Password": "Forgot Password",
  "OR": "OR",
  "Email": "Email",
  "Phone number": "Phone number",
  "Password": "Password",
  "Confirm password": "Confirm password",
  "Search": "Search",
  "Offer": "Offer",
  "Offering": "Offering",
  'Tithe': 'Tithe',
  "Project": "Project",
  'Daily Script': 'Daily Script',
  "Setting": "Setting",
  "Transactions": "Transactions",
  "Notifications": "Notifications",
  "Back": "Back",
  'Churches': 'Churches',
  'Donate': 'Donate',
  'Custom Amount': 'Custom Amount',
  'Projects': 'Projects',
  "NoProjects": "There is no projects.",
  "NoChurches": "There is no churches.",
  "Notification": "Notification",
  "Title": "Title",
  "Description": "Description",
  'Donate Amount': 'Donate Amount',
  'Transaction': 'Transaction',
  "Transaction ID": "Transaction ID",
  "Church Name": "Church Name",
  "Project Name": "Project Name",
  "Donate Date and Time": "Donate Date and Time",
  'Profile': 'Profile',
  'Full Name': 'Full Name',
  'Email': 'Email',
  'Phone Number': 'Phone Number',
  'Address': 'Address',
  'Birthday': 'Birthday',
  'Update Profile': 'Update Profile',
  'Security': 'Security',
  'Old Password': 'Old Password',
  'New Password': 'New Password',
  'Password' : 'Password',
  'Password updated.' : 'Password updated.',
  'Confirm Password': 'Confirm Password',
  'Update Password': 'Update Password',
  'Share': 'Share',
  'Failed' : 'Failed',
  'Succeed' : 'Succeed',
  'InvalidEmail' : 'Please enter a valid email address.',
  "CheckTerms" : "Please check Terms & Conditions!",
  'NamePassNull' : 'Please enter an user name and password.',
  'UserPhonePassNull' : 'Please fill all informations.',
  'Login Failed' : 'Login Failed',
  'UserCancelLogin' : 'User cancelled the login process',
  'AccessTokenObtain' : 'The access token was not obtained correctly.',
  'PasswordMismatch' : 'Passwords mismatched.',
  'Incorrect password' : 'Incorrect password',
  'AmountNull': 'Please choose or enter your amount.',
  'ImageUploaded' : 'Image uploaded.',
  "EnterPass" : "Please enter your password.",
  "Wrong Password" : "Wrong Password",
  "Login Succeed" : "Login Succeed.",
  "Profile updated" : "Profile updated.",
  "English" : "English",
  "French" : "French",
  "Transaction List" : "Transaction List",
  "Church created": "Church created.",
  "Project created": "Project created.",
  "Church List": "Church List",
  "Church searched": "Church searched.",
  "Church deleted": "Church deleted.",
  "Project deleted": "Project deleted.",
  "Project updated": "Project updated.",
  "Church updated": "Church updated.",
  "Notification created": "Notification created.",
  "Notification updated": "Notification updated.",
  "Notification List": "Notification List",
  "Notification": "Notification",
  "Read a notification": "Read a notification",
  "Transaction completed": "Transaction completed",
  "Transaction List": "Transaction List",
  "Transaction searched":  "Transaction searched.",
  "User List": "User List",
  "User deleted":  "User deleted.",
  "Transaction created.": "Transaction created.",
  "Verify": "Verify",
  'Reset password verification' : 'Reset password verification',
  "Resend code": "Resend code",
  "6 digit code": "6 digit code",
  "RegisterVerifyDesc": "A verification code has been sent to you via email. Please verify that 6 digit code below to continue.",
  "Verify Failed" : "Verify Failed",
  "New Password": "New Password",
  "New Confirm Password": "New Confirm Password",
  "SendCodeSucceed": "The verification code is sent successfully." ,
  
  "Terms Title" : 'Terms and Conditions of Use for the "Mon Eglise" Application',
  "Terms description" : 'By using the "Mon Eglise" application, you agree to the following terms and conditions:',
  "Terms subtitle1": "1. Acceptance of Terms of Use",
  "Terms subdescription1" : "By using this application, you agree to be bound by these terms and conditions of use. If you do not agree to these terms, please do not use the application.",
  "Terms subtitle2": "2. Authorized Use",
  "Terms subdescription2" : 'The "Mon Eglise" application is intended for use by members and supporters of our churches, as well as anyone interested in our activities and values. Any use of the application for illegal or unauthorized purposes is strictly prohibited.',
  "Terms subtitle3": "3. Intellectual Property",
  "Terms subdescription3" : 'All content in the "Mon Eglise" application, such as text, graphics, logos, images, audio, and video clips, is the property of the church or its content providers and is protected by intellectual property laws.',
  "Terms subtitle4": "4. Privacy and Data Collection",
  "Terms subdescription4" : "We respect your privacy and are committed to protecting your personal information in accordance with our privacy policy. By using the application, you consent to the collection, processing, and use of your personal data in accordance with our privacy policy.",
  "Terms subtitle5": "5. Consent for the Collection of Personal Data",
  "Terms subdescription5" : "By using this application, you consent to the collection, processing, and use of your personal data in accordance with the Mon Eglise privacy policy.",
  "Terms subtitle6": "6. Limitation of Liability",
  "Terms subdescription6" : "The use of the application is at your own risk. The church shall not be liable for any direct, indirect, incidental, special, or consequential damages arising from the use or inability to use the application.",
  "Terms subtitle7": "7. Changes to the Terms of Use",
  "Terms subdescription7" : "The Mon Eglise reserves the right to modify or replace these terms at any time. It is your responsibility to regularly check for updates to the terms of use. Continued use of the application after any modifications constitutes your acceptance of those changes.",
  "Terms subtitle8": "8. Contact",
  "Terms subdescription8" : "If you have any questions regarding these terms and conditions or our privacy policy, please contact us at the address provided on the Mon Eglise website monegliseci.com.",
  "Terms bottom title" : `Use of Cookies and Personal Data`,
  "Terms bottom description" :`This website uses cookies and similar technologies to process personal data. These processes include integrating content and services provided by partners, analyzing website usage, personalized advertising, and integration with social networks. Up to 15 partners may be involved in these processes. You are free to accept or refuse. Your consent is optional, not essential for using the website, and can be canceled or modified at any time by clicking on the icon displayed at the bottom left.`,
  "Agree Terms & Conditions" : `Agree Terms & Conditions`,
  "Terms & Conditions" : `Terms & Conditions`,
  "I Read and again to" : `I Read and again to`,
  
  "New" : "New",
  '2 000 F CFA' : '2 000 F CFA',
  '10 000 F CFA' : '10 000 F CFA',
  '50 000 F CFA' : '50 000 F CFA',
  'This church is not found' : 'This church is not found.',
  'This project is not found' : 'This project is not found.',
  'This notification is not found' : 'This notification is not found.',
  'Managers list' : 'Managers list',
  'Role updated' : 'Role updated.',
  'Manager deleted' : 'Manager deleted.',
  'User already exists' : 'User already exists.',
  'PhoneExists' :  'This phone already exists.',
  'Signup succeed' : 'Signup succeed.',
  'VerifyIncorrect' : 'Verify code is incorrect.',
  'VerifyResent' : 'Verify code is resent.',
  'VerifySent' : 'Verify code is sent.',
  'PasswordIncorrect' : 'Password is incorrect.',
  'PasswordReset' : 'Password is reset.',
  'Send a code': 'Send a code',
  'SMSNotSent' : 'SMS is not sent.',
  'EnterPhone' : 'Please enter your phone number.',
  'EnterVerifyCode' : 'Please enter the verify code sent to your phone.',
  'EnterEmailorPhone' : 'Please enter your email or phone number.',
  'Next' : 'Next',
  'EnterValidEmailorPhone' : 'Please enter a valid email or phone number.',
  'Userdoesntexist' : `The user doesn't exist.`,
  'PhoneOwnerdoesntexist' : `The phone owner doesn't exist.`,
  'NoEmailAccount': `We couldn't find your account. Please check your email and try again.`,
  'VerifyCodeFailed' : 'Verify code is not sent.',
  'SubAdmin privileges have been set': 'SubAdmin privileges have been set.',
  'SubAdmin privileges have been unset': 'SubAdmin privileges have been unset.',
  'TransactionTitle': "%{type} transaction completed",
  'TransactionDesc' : `Your %{amount} %{type} has been completed for the %{churchName}.`,
  'UpdateRoleComplete': `-Churches : %{churchNames} \n-Projects Permission : %{churchPermission} \n-Notification Permission : %{notificationPermission} \n-Transactions Permission : %{transactionPermission}`
}

const FRTranslates = {
  "Log In": "Se connecter",
  "Sign Up": "S'inscrire",
  "Sign Out": "Se déconnecter",
  "Home": "Eglise",
  "Email or Phone number": "Email ou numéro de téléphone",
  "Password": "Mot de passe",
  "Forgot Password": "Mot de passe oublié",
  "OR": "OU",
  "Email": "E-mail",
  "Phone number": "Numéro de téléphone",
  "Password": "Mot de passe",
  "Confirm password": "Confirmez le mot de passe",
  "Search": "Recherche",
  "Offer": "Offrandes",
  "Offering": "Offrandes",
  'Tithe': 'Dîme',
  "Project": "Project",
  'Daily Script': 'Script quotidien',
  "Setting": "Paramètre",
  "Transactions": "Transactions",
  "Notifications": "Notifications",
  "Back": "Retour",
  'Churches': 'Des églises',
  'Donate': 'Faire un don',
  'Custom Amount': 'Montant personnalisé',
  'Projects': 'Projects',
  "NoProjects": "Il n'y a aucun projet.",
  "NoChurches": "Il n'y a pas d'églises.",
  "Notification": "Notification",
  "Title": "Titre",
  "Description": "Description",
  'Donate Amount': 'Montant du don',
  'Transaction': 'Transaction',
  "Transaction ID": "identifiant de transaction",
  "Church Name": "Nom de l'église",
  "Project Name": "nom du projet",
  "Donate Date and Time": "Date et heure du don",
  'Profile': 'Profil',
  'Full Name': 'Nom et prénom',
  'Email': 'E-mail',
  'Phone Number': 'Numéro de téléphone',
  'Address': 'Address',
  'Birthday': 'Anniversaire',
  'Update Profile': 'Mettre à jour le profil',
  'Security': 'Sécurité',
  'Old Password': 'ancien mot de passe',
  'New Password': 'nouveau mot de passe',
  'Password' : 'Mot de passe',
  'Password updated.' : 'Mot de passe mis à jour.',
  'Confirm Password': 'Confirmez le mot de passe.',
  'Update Password': 'Mettre à jour le mot de passe',
  'Share': 'Partager',
  'Failed' : 'Échoué',
  'Succeed' : 'réussie', 
  'InvalidEmail' : `S'il vous plaît, mettez une adresse email valide.`,
  "CheckTerms" : "Veuillez consulter les conditions générales!",
  'NamePassNull' : `Veuillez saisir un nom d'utilisateur et un mot de passe.`,
  'UserPhonePassNull' : 'Veuillez remplir toutes les informations.',
  'Login Failed' : 'La connexion a échoué',
  'UserCancelLogin' : `L'utilisateur a annulé le processus de connexion`,
  'AccessTokenObtain' : `Le jeton d'accès n'a pas été obtenu correctement.`,
  'PasswordMismatch' : 'Les mots de passe ne correspondent pas.',
  'Incorrect password' : 'Mot de passe incorrect',
  'AmountNull': 'Veuillez choisir ou saisir votre montant.',
  'ImageUploaded' : 'Image téléchargée.',
  "EnterPass" : "S'il vous plait entrez votre mot de passe.",
  "Wrong Password" : "Mauvais mot de passe",
  "Login Succeed" : "Connexion réussie.",
  "Profile updated" : "Profil mis à jour.",
  "English" : "Anglais",
  "French" : "Français",
  "Transaction List" : "Liste des transactions",
  "Church created": "Église créée.",
  "Project created": "Projet créé.",
  "Church List": "Liste des églises",
  "Church searched": "L'église a été fouillée.",
  "Church deleted": "Église supprimée.",
  "Project deleted": "Projet supprimé.",
  "Project updated": "Projet mis à jour.",
  "Church updated": "Église mise à jour.",
  "Notification created": "Notification créée.",
  "Notification updated": "Notification mise à jour.",
  "Notification List": "Liste des notifications",
  "Notification": "Notification",
  "Read a notification": "Lire une notification",
  "Transaction completed": "Transaction terminée.",
  "Transaction List": "Liste des transactions",
  "Transaction searched":  "Transaction recherchée.",
  "User List": "liste d'utilisateur",
  "User deleted":  "Utilisateur supprimé.",
  "Transaction created.": "Transaction créée.",
  "Verify": "Vérifier",
  'Reset password verification' : 'Réinitialiser la vérification du mot de passe',
  "Resend code": "Renvoyer le code",
  "6 digit code": "Code à 6 chiffres",
  "RegisterVerifyDesc": "Un code de vérification vous a été envoyé par e-mail. Veuillez vérifier le code à 6 chiffres ci-dessous pour continuer.",
  "Verify Failed" : "Échec de la vérification",
  "New Password": "nouveau mot de passe",
  "New Confirm Password": "Nouveau mot de passe de confirmation",
  "SendCodeSucceed": "Le code de vérification est envoyé avec succès." ,

  "Terms Title" : `Conditions générales d'utilisation de l'application "Mon Eglise"`,
  "Terms description" : `En utilisant l'application "Mon Eglise", vous acceptez les termes et conditions suivants`,
  "Terms subtitle1": "1. Acceptation des conditions d'utilisation",
  "Terms subdescription1" : `En utilisant cette application, vous acceptez d'être lié par ces termes et conditions d'utilisation. Si vous n'acceptez pas ces conditions, veuillez ne pas utiliser l'application`,
  "Terms subtitle2": `2. Utilisation autorisée`,
  "Terms subdescription2" : `L'application "Mon Eglise" est destinée à être utilisée par les membres et sympathisants de nos églises, ainsi que par toute personne intéressée par nos activités et nos valeurs. Toute utilisation de l'application à des fins illégales ou non autorisées est strictement interdite.`,
  "Terms subtitle3": "3. Propriété intellectuelle",
  "Terms subdescription3" : `Tout le contenu de l'application "Mon Eglise", tel que les textes, graphiques, logos, images, audio et clips vidéo, est la propriété de l'église ou de ses fournisseurs de contenu et est protégé par les lois sur la propriété intellectuelle.`,
  "Terms subtitle4": "4. Confidentialité et collecte de données",
  "Terms subdescription4" : `Nous respectons votre vie privée et nous engageons à protéger vos informations personnelles conformément à notre politique de confidentialité. En utilisant l'application, vous consentez à la collecte, au traitement et à l'utilisation de vos données personnelles conformément à notre politique de confidentialité`,
  "Terms subtitle5": "5. Consentement à la collecte de données personnelles",
  "Terms subdescription5" : `En utilisant cette application, vous consentez à la collecte, au traitement et à l'utilisation de vos données personnelles conformément à la politique de confidentialité de Mon Eglise.`,
  "Terms subtitle6": "6. Limitation de responsabilité",
  "Terms subdescription6" : `L'utilisation de l'application est à vos propres risques. L'église ne sera pas responsable des dommages directs, indirects, accessoires, spéciaux ou consécutifs résultant de l'utilisation ou de l'impossibilité d'utiliser l'application.`,
  "Terms subtitle7": "7. Modifications des conditions d'utilisation",
  "Terms subdescription7" : `Mon Eglise se réserve le droit de modifier ou de remplacer ces conditions à tout moment. Il est de votre responsabilité de vérifier régulièrement les mises à jour des conditions d'utilisation. La poursuite de l'utilisation de l'application après toute modification constitue votre acceptation de ces modifications`,
  "Terms subtitle8": "8. Contacter",
  "Terms subdescription8" : `Si vous avez des questions concernant les présentes conditions générales ou notre politique de confidentialité, veuillez nous contacter à l'adresse indiquée sur le site Mon Eglise monegliseci.com.`,
  "Terms bottom title" : `Utilisation des cookies et des données personnelles`,
  "Terms bottom description" :`Ce site Web utilise des cookies et des technologies similaires pour traiter les données personnelles. Ces processus incluent l'intégration du contenu et des services fournis par les partenaires, l'analyse de l'utilisation du site Web, la publicité personnalisée et l'intégration avec les réseaux sociaux. Jusqu'à 15 partenaires peuvent être impliqués dans ces processus. Vous êtes libre d'accepter ou de refuser. Votre consentement est facultatif, non indispensable à l'utilisation du site Internet, et peut être annulé ou modifié à tout moment en cliquant sur l'icône affichée en bas à gauche.`,
  "Agree Terms & Conditions" : `Accepter les termes et conditions`,
  "Terms & Conditions" : `termes et conditions`,
  "I Read and again to" : `J'ai lu et encore à`,

  "New" : "Nouveau",
  '2 000 F CFA' : '2 000 F CFA',
  '10 000 F CFA' : '10 000 F CFA',
  '50 000 F CFA' : '50 000 F CFA',
  'This church is not found' : 'Cette église est introuvable.',
  'This project is not found' : 'Ce projet est introuvable.',
  'This notification is not found' : 'Cette notification est introuvable.',
  'Managers list' : 'Liste des managers',
  'Role updated' : 'Rôle mis à jour.',
  'Manager deleted' : 'Gestionnaire supprimé.',
  'User already exists' : `L'utilisateur existe déjà.`,
  'PhoneExists' : `Ce téléphone existe déjà.`,
  'Signup succeed' : `L'inscription est réussie.`,
  'VerifyIncorrect' : `Vérifiez que le code est incorrect.`,
  'VerifyResent' : `Vérifiez que le code est renvoyé.`,
  'VerifySent' : 'Vérifier que le code est envoyé.',
  'PasswordIncorrect' : 'Le mot de passe est incorrect.',
  'PasswordReset' : `Le mot de passe est réinitialisé`,
  'Send a code' : 'Envoyer un code',
  'SMSNotSent' : `Le SMS n'est pas envoyé`,

  'EnterPhone' : 'Veuillez entrer votre numéro de téléphone.',
  'EnterVerifyCode' : 'Veuillez saisir le code de vérification envoyé sur votre téléphone.',
  'EnterEmailorPhone' : `Veuillez entrer votre email ou votre numéro de téléphone.`,
  'Next' : 'Suivante',
  'EnterValidEmailorPhone' : 'Veuillez saisir une adresse e-mail ou un numéro de téléphone valide.',
  'Userdoesntexist' : `L'utilisateur n'existe pas.`,
  'PhoneOwnerdoesntexist' : `Le propriétaire du téléphone n'existe pas.`,
  'NoEmailAccount': `Nous n'avons pas trouvé votre compte. Veuillez vérifier votre courrier électronique et réessayer.`,
  'VerifyCodeFailed' : `Vérifiez que le code n'est pas envoyé`,

  'SubAdmin privileges have been set': 'Les privilèges du sous-administrateur ont été définis.',
  'SubAdmin privileges have been unset': `Les privilèges du sous-administrateur n'ont pas été envoyés.`,
  'TransactionTitle': "%{type} transaction completed",
  'TransactionDesc' : `Your %{amount} %{type} has been completed for the %{churchName}.`,
  'UpdateRoleComplete': `-Churches : %{churchNames} \n-Projects Permission : %{churchPermission} \n-Notification Permission : %{notificationPermission} \n-Transactions Permission : %{transactionPermission}`
}


export { IMAGE, ENTranslates, FRTranslates };
